spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        hbm2ddl:
          create_namespaces: true
        default_schema: upress

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        orm:
          jpa: DEBUG